using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.IO;
using CryptoApi;

namespace SharpHash
{
    public partial class FileHashValidator : Form
    {
        int time = 0;
        public FileHashValidator()
        {
            InitializeComponent();
        }

        private void TimeRunning_Tick(object sender, EventArgs e)
        {
            time++;
        }

        private void OHF_Click(object sender, EventArgs e)
        {
            openFileDialog.ShowDialog();
            HashFilePath.Text = openFileDialog.FileName;
        }

        private void OpenFileFV_Click(object sender, EventArgs e)
        {
            openFileDialog.ShowDialog();
            FTVPath.Text = openFileDialog.FileName;
        }

        private void val_go_Click(object sender, EventArgs e)
        {
            TimeRunning.Enabled = true;
            string uvhash;
            if (hash.Text == "")
            {
                StreamReader hf = new StreamReader(HashFilePath.Text);
                uvhash = hf.ReadToEnd();
                hf.Close();
            }
            else
            {
                uvhash = hash.Text;
            }
            StreamReader ftv = new StreamReader(FTVPath.Text);
            string ftvContents = ftv.ReadToEnd();
            ftv.Close();
            string vh = Hash.CryptoGeneric(Algorithm.Text, ftvContents, true);
            string veredict;
            if (vh == uvhash)
            {
                veredict = "Compatible";
                TimeRunning.Enabled = false;
            }
            else
            {
                veredict = "Uncompatible";
                TimeRunning.Enabled = false;
            }
            results.Text = "Test results:\nFile " + FTVPath.Text + " Was compared to the following hash " + uvhash + " usign the " + Algorithm.Text + " as the hash algorithm for the comprarison.\nFinal veredict the the hashes are " + veredict + "\nTest finished in " + time + " ms" + "\nReport generated by CodeWisard's hash tools.";
            results.Text = results.Text + "\nDebug info raw file validated:\n+===================================+\n" + ftvContents + "\n+===================================+\n The hash generated for it was:\n" + vh + "\nAnd it was compared to this\n" + uvhash;
            saveReportTrigger.Enabled = true;
        }

        private void saveReportTrigger_Click(object sender, EventArgs e)
        {
            saveFileDialog.ShowDialog();
            string path = saveFileDialog.FileName;
            File.WriteAllText(path, results.Text);
        }
    }
}
